config/routes.rb
Rails.application.routes.draw do

  namespace :admin do
    resources :order_details, only:[:update]
  end

  namespace :admin do
    resources :orders, only:[:show, :update]
  end

  namespace :admin do
    resources :customers, only:[:index, :show, :edit, :update]
  end

  namespace :admin do
    resources :items, except: [:destroy] do
     resources :comments, only:[:index, :edit, :update, :destroy], shallow: true
    end
  end

  namespace :admin do
    get 'homes/top'
  end

  scope module: 'public' do
    get 'customers/mypage', to: 'customers#show'
    get 'customers/edit', to: 'customers#edit'
    patch 'customers/update'
    get 'customers/unsubscribe'
    patch 'customers/withdraw'
  end

  scope module: 'public' do
    get 'orders/thanks'
    post 'orders/confirm'
    resources :orders, only:[:new, :create, :index, :show]
  end
  scope module: 'public' do
    delete 'cart_items/empty'
    resources :cart_items, only:[:index, :create, :update, :destroy]
  end

  scope module: 'public' do
    get 'items/search'
    resources :items, only:[:index, :show] do
     resources :comments, except:[:show],shallow: true
    end
  end

  scope module: 'public' do
    root to: 'homes#top'
    get 'about', to: 'homes#about'
    get 'policy', to: 'homes#policy'
  end

  scope module: 'public' do
    resources :contacts, only: [:new, :create]
  end

devise_for :customers,skip: [:passwords], controllers: {
  registrations: "public/registrations",
  sessions: 'public/sessions'
}

devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
  sessions: "admin/sessions"
}

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :item
  belongs_to :customer


  validates :rate, numericality: {
    less_than_or_equal_to: 5,
    greater_than_or_equal_to: 0.5}, presence: true

  def avg_score
    unless self.comments.empty?
      comments.average(:rate_id).round(1)
    else
      0.0
    end
  end

  def avg_score_percentage
   unless self.comments.empty?
     comments.average(:rate_id).round(1).to_f*100/5
   else
     0.0
   end
  end

end

app/controllers/admin/comments_controller.rb
class Admin::CommentsController < ApplicationController
  def index
    @item = Item.find(params[:item_id])
    @comments = @item.comments
  end

  def edit
    @comment = Comment.find(params[:id])
  end

  def destroy
    @comment = Comment.find(params[:id])
    @item = @comment.item
    @comment.destroy
    redirect_to admin_item_comments_path(@item)
  end

  def update
    comment = Comment.find(params[:id])
    item = comment.item
    comment.update(comment_params)
    redirect_to admin_item_comments_path(item)
  end

  private
  def comment_params
    params.require(:comment).permit(:item_id, :comment_content, :rate)
  end
end

app/helpers/admin/comments_helper.rb
module Admin::CommentsHelper
end

app/views/admin/comments/edit.html.erb
<div class="container">
 <div class="row">
    <p class="h4 col-sm-8 offset-sm-2 mt-4 mb-4 text-secondary">レビュー編集</p>
 </div>

 <%= form_with model: @comment, url: admin_comment_path(@comment), local:true do |f| %>
 <div class="row">
    <label for="rate": class="col-sm-2 offset-sm-2 mt-1 text-secondary">星評価</label>
    <div id="rate-<%= @comment.id %>"></div>
    <script>
          $('#rate-<%= @comment.id %>').raty({
            size: 33,
            starOff:  '<%= asset_path('star-off.png') %>',
            starOn : '<%= asset_path('star-on.png') %>',
            starHalf: '<%= asset_path('star-half.png') %>',
            half: true,
            score: <%= @comment.rate %>,
            scoreName: 'comment[rate]',
        });
    </script>

 </div>
 <div class="row">
    <label for="comment_content": class="col-sm-2 offset-sm-2 mt-3 text-secondary">レビュー</label>
    <div class="col-sm-8 mt-3 "><%= f.text_area :comment_content, size: "45x4" %></div>
 </div>
 <div class="row">
    <div class="col-sm-2 offset-sm-4 my-4">
      <%= f.submit :編集内容を保存, class: 'btn btn-outline-success py-2 px-3' %>
    </div>
 </div>
 <% end %>
</div>

app/views/admin/comments/index.html.erb
<div class="container">
  <div class="row">
    <p class="h4 offset-sm-2 text-secondary"><%= @item.name %> のレビュー 一覧</p>
  </div>

  <div class="row pb-5">
    <% @comments.each do |comment| %>
    <div class="card col-sm-8 offset-sm-2 mt-2">
    <p class="mb-auto mt-2 text-secondary">投稿者：<%= link_to comment.customer.nickname, admin_customer_path(comment.customer), class: "link-line" %> さん</p>
    <div id="rate-<%= comment.id %>"></div>
    <script>
          $('#rate-<%= comment.id %>').empty();
          $('#rate-<%= comment.id %>').raty({
            size: 36,
            starOff:  '<%= asset_path('star-off.png') %>',
            starOn : '<%= asset_path('star-on.png') %>',
            starHalf: '<%= asset_path('star-half.png') %>',
            half: true,
            score: <%= comment.rate %>,
        });
    </script>
    <p class="border-top mt-2 text-secondary">レビュー：<%= comment.comment_content %></p>
    <div class="button text-right mb-2">
    <%= link_to "編集", edit_admin_comment_path(comment), class: 'btn btn-outline-success' %>
    <%= link_to "削除", admin_comment_path(comment), method: :delete, class: 'btn btn-outline-danger' %>
    </div>
   </div>
   <% end %>
 </div>
</div>