config/routes.rb
Rails.application.routes.draw do

  namespace :admin do
    resources :order_details, only:[:update]
  end

  namespace :admin do
    resources :orders, only:[:show, :update]
  end

  namespace :admin do
    resources :customers, only:[:index, :show, :edit, :update]
  end

  namespace :admin do
    resources :items, except: [:destroy] do
     resources :comments, only:[:index, :edit, :update, :destroy], shallow: true
    end
  end

  namespace :admin do
    get 'homes/top'
  end

  scope module: 'public' do
    get 'customers/mypage', to: 'customers#show'
    get 'customers/edit', to: 'customers#edit'
    patch 'customers/update'
    get 'customers/unsubscribe'
    patch 'customers/withdraw'
  end

  scope module: 'public' do
    get 'orders/thanks'
    post 'orders/confirm'
    resources :orders, only:[:new, :create, :index, :show]
  end
  scope module: 'public' do
    delete 'cart_items/empty'
    resources :cart_items, only:[:index, :create, :update, :destroy]
  end

  scope module: 'public' do
    get 'items/search'
    resources :items, only:[:index, :show] do
     resources :comments, except:[:show],shallow: true
    end
  end

  scope module: 'public' do
    root to: 'homes#top'
    get 'about', to: 'homes#about'
    get 'policy', to: 'homes#policy'
  end

  scope module: 'public' do
    resources :contacts, only: [:new, :create]
  end

devise_for :customers,skip: [:passwords], controllers: {
  registrations: "public/registrations",
  sessions: 'public/sessions'
}

devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
  sessions: "admin/sessions"
}

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/item.rb
class Item < ApplicationRecord
  has_one_attached :image_id
  has_many :cart_items
  has_many :order_details
  has_many :comments, dependent: :destroy

  def add_tax_price
  (self.price * 1.10).floor
  end

  def avg_score
    unless self.comments.empty?
      comments.average(:rate).round(1)
    else
      0.0
    end
  end

  def self.item_comment_ranks(limit)
    self.find(Comment.group(:item_id).order("rate DESC").pluck(:item_id)).first(limit)
  end

end

app/controllers/admin/items_controller.rb
class Admin::ItemsController < ApplicationController
  before_action :authenticate_admin!
  def index
    @items = Item.page(params[:page]).per(10)
  end

  def new
    @item = Item.new
  end

  def create
    @item = Item.new(item_params)
    if @item.save
     redirect_to admin_item_path(@item.id)
    else
     render :new
    end
  end

  def show
    @item = Item.find(params[:id])
    @comments = @item.comments
  end

  def edit
    @item = Item.find(params[:id])
  end

  def update
    @item = Item.find(params[:id])
    @item.update(item_params)
    redirect_to admin_item_path(@item.id)
  end

  private
  def item_params
    params.require(:item).permit(:image_id, :name, :volume, :price, :introduction, :blend_example, :blend_flag)
  end
end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/views/admin/items/edit.html.erb
<div class="container">
 <div class="row">
  <p class="h4 col-sm-2 offset-sm-2 text-secondary">商品編集</p>
 </div>


<%= form_with model: @item, url: admin_item_path(@item.id), local:true do |f| %>
<div class="row">
 <div class="col-sm-2 offset-sm-2 mt-3 text-secondary">
  <p>商品画像</p>
 </div>
 <div class="col-sm-4 mt-3 text-secondary">
  <%= f.file_field :image_id, accept: "image/*" %>
 </div>
</div>

<div class="row">
 <div class="col-sm-2 offset-sm-2 mt-3 text-secondary">
  <p>商品名</p>
 </div>
 <div class="col-sm-4 mt-3 text-secondary">
  <%= f.text_field :name %>
 </div>
</div>

<div class="row">
 <div class="col-sm-2 offset-sm-2 mt-3 text-secondary">
  <p>容量</p>
 </div>
 <div class="col-sm-4 mt-3 text-secondary">
  <%= f.text_field :volume %>
 </div>
</div>

<div class="row">
 <div class="col-sm-2 offset-sm-2 mt-3 text-secondary">
  <p>商品説明</p>
 </div>
 <div class="col-sm-4 mt-3 text-secondary">
  <%= f.text_area :introduction, size: "40x7" %>
 </div>
</div>
<div class="row">
 <div class="col-sm-2 offset-sm-2 mt-3 text-secondary">
  <p>おすすめブレンド</p>
 </div>
 <div class="col-sm-4 mt-3 text-secondary">
  <%= f.text_area :blend_example, size: "40x3" %>
 </div>
</div>
<div class="row">
 <div class="col-sm-2 offset-sm-2 mt-3 text-secondary">
  <p>税抜価格</p>
 </div>
 <div class="col-sm-4 mt-3 text-secondary">
  <%= f.text_field :price %>円
 </div>
</div>
<div class="row">
 <div class="col-sm-2 offset-sm-2 mt-3 text-secondary">
  <p>商品ジャンル</p>
 </div>
 <div class="col-sm-4 mt-3">
   <%= f.radio_button :blend_flag, true %>
   <%= f.label :blend_flag,"ブレンド商品", value: true %>
   <%= f.radio_button :blend_flag, false %>
   <%= f.label :blend_flag,"通常商品", value: false %><br>
 </div>
</div>

<div class="row pb-5">
 <div class="col-sm-2 offset-sm-2 mt-3 "></div>
  <%= f.submit :変更を保存, class: 'btn btn-outline-success col-sm-4 btn-block py-2 px-4' %>
 </div>
</div>
<% end %>
</div>

app/views/admin/items/index.html.erb
<div class="container">
  <div class="row">
   <p class="h4 col-sm-2 offset-sm-2 mb-4 text-secondary">商品一覧</p>
  </div>

  <div class="row">
    <div class="col-sm-2 offset-sm-2 mt-2">
      <%= link_to "商品登録", new_admin_item_path, class: "btn btn-outline-success " %>
    </div>
  </div>

  <div class="row">
    <table class="col-sm-8 offset-sm-2 mt-3 text-secondary table-hover table-responsive-sm table-striped center-block">
      <thead>
        <tr>
         <th class="py-2 px-4">商品ID</th>
         <th class="py-2 px-4">商品名</th>
         <th class="py-2 px-4">容量</th>
         <th class="py-2 px-4">税抜価格</th>
         <th class="py-2 px-4">商品ジャンル</th>

        </tr>
      </thead>
      <tbody>
        <% @items.each do |item| %>
         <tr>
           <td class="py-2 px-4"><%= item.id %></td>
           <td class="py-2 px-4"><%= link_to item.name, admin_item_path(item.id), class: "link-line" %></td>
           <td class="py-2 px-4"><%= item.volume %></td>
           <td class="py-2 px-4"><%= item.price.to_s (:delimited) %>円</td>
           <td class="py-2 px-4">
             <% if item.blend_flag == true %>
              <%= blend_flag = "ブレンド商品" %>
             <% else %>
              <%= blend_flag = "通常商品" %>
             <% end %>
          </td>
         </tr>
        <% end %>
      </tbody>
    </table>
    <div class="pagination col-sm-8 offset-sm-2 py-3">
    <%= paginate @items %>
    </div>
  </div>
</div>

app/views/admin/items/new.html.erb
<div class="container">
 <div class="row">
  <p class="h4 col-sm-4 offset-sm-2 text-secondary mb-4">商品新規登録</p>
 </div>


<%= form_with model: @item, url:admin_items_path, local:true do |f| %>
<div class="row">
 <div class="col-sm-2 offset-sm-3 mt-4 text-secondary">
   <p>商品画像</p>
 </div>
 <div class="col-sm-4 mt-4">
   <%= f.file_field :image_id, accept: "image/*" %>
 </div>
</div>

<div class="row">
 <div class="col-sm-2 offset-sm-3 text-secondary">
  <p>商品名</p>
 </div>
 <div class="col-sm-4">
  <%= f.text_field :name, size: "35"%>
 </div>
</div>

<div class="row">
 <div class="col-sm-2 offset-sm-3 text-secondary">
  <p>容量</p>
 </div>
 <div class="col-sm-4">
  <%= f.text_field :volume, size: "20" %>
 </div>
</div>

<div class="row">
 <div class="col-sm-2 offset-sm-3 text-secondary">
  <p>商品説明</p>
 </div>
 <div class="col-sm-4">
  <%= f.text_area :introduction, size: "34"%>
 </div>
</div>

<div class="row">
 <div class="col-sm-2 offset-sm-3 text-secondary">
  <p>おすすめブレンド</p>
 </div>
 <div class="col-sm-4">
  <%= f.text_area :blend_example, size: "34"%>
 </div>
</div>

<div class="row">
 <div class="col-sm-2 offset-sm-3 text-secondary">
  <p>税抜価格</p>
 </div>
 <div class="col-sm-5">
  <p><%= f.text_field :price, size: "20" %> 円</p>
 </div>
</div>
<div class="col-sm-4 offset-sm-5">
 <%= f.radio_button :blend_flag, true %>
 <%= f.label :blend_flag, "ブレンド商品", value: true %>
 <%= f.radio_button :blend_flag,false %>
 <%= f.label :blend_flag, "通常商品", value: false %>
</div>

<div class="col-sm-2 offset-sm-5 py-5">
 <%= f.submit :新規登録, class: 'btn btn-outline-success  px-5 px-3' %>
</div>

<% end %>
</div>

app/views/admin/items/show.html.erb
<div class="container">
 <div class="row mt-5">
  <div class="image col-sm-4">
    <%= image_tag @item.image_id, size: "300x240", class: "img-fluid" %>
    <div class="average-review-rating mt-3" data-score=<%= @item.avg_score %>></div>
      <p>レビュー
      <%= link_to admin_item_comments_path(@item), class: "link-line" do %>（ <%= @item.comments.count %> ）
      <% end %></p>
  </div>

  <div class="col-sm-7">
    <table class="table-responsive-sm item-show">
      <thead>
        <tr><th class="w-50 py-2 px-2">商品名</th><td class="w-50 h5"><%= @item.name %></td></tr>
        <tr><th class="py-2 px-2">容量</th><td><%= @item.volume %></td></tr>
        <tr><th class="py-2 px-2">税込価格（税抜価格)</th><td><%= @item.add_tax_price.to_s (:delimited) %>
                                            (
                                           <%= @item.price.to_s (:delimited) %>) 円</td></tr>
        <tr><th class="align-baseline py-2 px-2">製品ジャンル</th><td class="align-baseline py-2"><% if @item.blend_flag == true %>
                                     <p><%= @item.blend_flag ="ブレンド商品" %></p>
                                     <% else %>
                                     <p><%= @item.blend_flag ="通常商品" %></p>
                                     <% end %></td></tr>
        <tr><th class="align-baseline py-2 px-2">商品説明</th><td class="py-2"><%= safe_join(@item.introduction.split("\n"),tag(:br)) %></td></tr>
        <tr><th class="align-baseline py-4 px-2">おすすめブレンド</th><td class="py-4"><%= @item.blend_example %></td></tr>
      </thead>
    </table>
    <div class="text-right mt-2 mb-5"><%= link_to "編集する", edit_admin_item_path(@item.id), class: 'btn btn-outline-success mt-1' %></div>
  </div>
 </div>
</div>
 <script>
  $('.average-review-rating').empty();
  $('.average-review-rating').raty({
    readOnly: true,
    starOn: "<%= asset_path('star-on.png') %>",
    starOff: "<%= asset_path('star-off.png') %>",
    starHalf: "<%= asset_path('star-half.png') %>",
    score: function() {
      return $(this).attr('data-score')
    }
  });
　</script>