config/routes.rb
Rails.application.routes.draw do

  namespace :admin do
    resources :order_details, only:[:update]
  end

  namespace :admin do
    resources :orders, only:[:show, :update]
  end

  namespace :admin do
    resources :customers, only:[:index, :show, :edit, :update]
  end

  namespace :admin do
    resources :items, except: [:destroy] do
     resources :comments, only:[:index, :edit, :update, :destroy], shallow: true
    end
  end

  namespace :admin do
    get 'homes/top'
  end

  scope module: 'public' do
    get 'customers/mypage', to: 'customers#show'
    get 'customers/edit', to: 'customers#edit'
    patch 'customers/update'
    get 'customers/unsubscribe'
    patch 'customers/withdraw'
  end

  scope module: 'public' do
    get 'orders/thanks'
    post 'orders/confirm'
    resources :orders, only:[:new, :create, :index, :show]
  end
  scope module: 'public' do
    delete 'cart_items/empty'
    resources :cart_items, only:[:index, :create, :update, :destroy]
  end

  scope module: 'public' do
    get 'items/search'
    resources :items, only:[:index, :show] do
     resources :comments, except:[:show],shallow: true
    end
  end

  scope module: 'public' do
    root to: 'homes#top'
    get 'about', to: 'homes#about'
    get 'policy', to: 'homes#policy'
  end

  scope module: 'public' do
    resources :contacts, only: [:new, :create]
  end

devise_for :customers,skip: [:passwords], controllers: {
  registrations: "public/registrations",
  sessions: 'public/sessions'
}

devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
  sessions: "admin/sessions"
}

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :name, presence: true
  validates :name_kana, presence: true
  validates :nickname, presence: true
  validates :email, presence: true
  validates :telephone_number, presence: true, numericality: { only_integer: true }
  validates :postal_code, presence: true, numericality: { only_integer: true }
  validates :address, presence: true
  validates :email, presence: true

  has_many :comments, dependent: :destroy
  has_many :cart_items
  has_many :orders
end

app/controllers/admin/customers_controller.rb
class Admin::CustomersController < ApplicationController
  before_action :authenticate_admin!

  def index
    @customers = Customer.page(params[:page]).per(10)
  end

  def show
    @customer = Customer.find(params[:id])
    @comments = @customer.comments.page(params[:page]).per(3)
  end

  def edit
    @customer = Customer.find(params[:id])
  end

  def update
    @customer = Customer.find(params[:id])
    @customer.update(customer_params)
    redirect_to admin_customer_path(@customer.id)
  end

  private
  def customer_params
    params.require(:customer).permit(:name, :name_kana, :nickname, :postal_code, :address, :email, :telephone_number, :is_active)
  end
end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/views/admin/customers/edit.html.erb
<div class="container">
  <div class="row">
   <p class="h4 col-sm-6 offset-sm-2 text-secondary"><%= @customer.name %>  様  顧客詳細編集</p>
  </div>

  <%= form_with model: @customer, url: admin_customer_path(@customer.id), local:true do |f| %>
  <div class="row mt-3 text-secondary">
    <p class="col-sm-3 offset-sm-2">会員ID</p>
    <div class="col-sm-7 h5">No.<%= @customer.id %></div>

    <p class="col-sm-3 offset-sm-2">氏名</p>
    <div class="col-sm-7"><%= f.text_field :name %></div>

    <p class="col-sm-3 offset-sm-2">フリガナ</p>
    <div class="col-sm-7"><%= f.text_field :name_kana %></div>

    <p class="col-sm-3 offset-sm-2">表示名</p>
    <div class="col-sm-7"><%= f.text_field :nickname %></div>

    <p class="col-sm-3 offset-sm-2">郵便番号</p>
    <div class="col-sm-7"><%= f.text_field :postal_code %></div>

    <p class="col-sm-3 offset-sm-2">住所</p>
    <div class="col-sm-7"><%= f.text_field :address, size: "65" %></div>

    <p class="col-sm-3 offset-sm-2">電話番号</p>
    <div class="col-sm-7"><%= f.text_field :telephone_number %></div>

    <p class="col-sm-3 offset-sm-2">メールアドレス</p>
    <div class="col-sm-7"><%= f.text_field :email %></div>

    <p class="col-sm-3 offset-sm-2">会員ステータス</p>
  <div class="col-sm-7"><%= f.radio_button :is_active, true %>
   <%= f.label :is_active,"有効", value: true %>
   <%= f.radio_button :is_active, false %>
   <%= f.label :is_active,"退会", value: false %></div>
   <div class="col-sm-3 offset-sm-5"><%= f.submit '変更を保存', class: 'btn btn-outline-success btn-block px-3 py-2' %></div>
　</div>
　<% end %>
</div>

app/views/admin/customers/index.html.erb
<div class="container">
  <div class="row">
   <p class="h4 col-sm-3 offset-sm-2 mt-3 text-secondary">顧客一覧</p>
  </div>
  <table class="table-bordered table-responsive-sm offset-sm-2  mt-3 center-block">
   <thead>
      <tr class="text-center text-secondary">
        <th class="py-2 px-2">会員ID</th>
        <th class="py-2 px-2">氏名</th>
        <th class="py-2 px-2">住所</th>
        <th class="py-2 px-2">メールアドレス</th>
        <th class="py-2 px-2">ステータス</th>
      </tr>
   </thead>
   <tbody>
    <% @customers.each do |customer| %>
      <tr class="text-center">
        <td class="py-2 px-2"><%= customer.id %></td>
        <td class="py-2 px-2 text-dark"><%= link_to customer.name, admin_customer_path(customer.id), class: "link-line" %></td>
        <td class="py-2 px-2">〒<%= customer.postal_code %> <%= customer.address %></td>
        <td class="py-2 px-2"><%= customer.email %></td>
        <td class="pt-3"><% if customer.is_active == true %>
                              <p class="font-weight-bold text-center"><%= is_active = "有効" %></p>
                              <% else %>
                              <p class="text-black-50 font-weight-bold text-center"><%= is_active = "退会" %></p>
                              <% end %>
        </td>
      </tr>
    <% end %>
   </tbody>
  </table>
  <div class="pagination col-sm-8 offset-sm-2 my-3">
    <%= paginate @customers %>
  </div>
 </div>
</div>

app/views/admin/customers/show.html.erb
<div class="bc">
<div class="container">
  <div class="row">
   <p class="h4 col-sm-4 offset-sm-3 text-secondary"><%= @customer.name %>　様　顧客詳細</p>
  </div>
  <div class="row">
   <div class="col-sm-5 offset-sm-7 mt-3">
    <%= link_to "編集する", edit_admin_customer_path(@customer.id), class: 'btn btn-outline-success' %>
   </div>
  </div>
  <div class="row">
    <div class="col-sm-10 offset-sm-1 mt-2">
    <table class="table-bordered table-responsive-sm border-dark mx-auto">
      <thead>
        <tr><th class="px-2 py-2 text-secondary">会員ID</th><td class="px-2"><%= @customer.id %></td></tr>
        <tr><th class="px-2 py-2 text-secondary">氏名</th><td class="px-2"><%= @customer.name %></td></tr>
         <tr><th class="px-2 py-2 text-secondary">フリガナ</th><td class="px-2"><%= @customer.name_kana %></td></tr>
         <tr><th class="px-2 py-2 text-secondary">表示名</th><td class="px-2"><%= @customer.nickname %></td></tr>
         <tr><th class="px-2 py-2 text-secondary">住所</th><td class="px-2 pr-5">〒<%= @customer.postal_code %> <%= @customer.address %></td></tr>
         <tr><th class="px-2 py-2 text-secondary">電話番号</th><td class="px-2"><%= @customer.telephone_number %></td></tr>
         <tr><th class="px-2 py-2 text-secondary">メールアドレス</th><td class="px-2"><%= @customer.email %></td></tr>
         <tr><th class="px-2 py-2 text-secondary">ステータス</th><td class="pt-2 px-2"><% if @customer.is_active == true %>
                              <p class="font-weight-bold"><%= is_active = "有効" %></p>
                              <% else %>
                              <p class="text-black-50 font-weight-bold"><%= is_active = "退会" %></p>
                              <% end %></td></tr>
      </thead>
    </table>
    </div>
  </div>
  <div class="row">
   <div class="col-sm-3 offset-sm-3 mt-4">
     <p class="h5  text-secondary">レビュー履歴</p>
   </div>
      <% @comments.each do |comment| %>
    <div class="card review-card col-sm-6 offset-sm-3 mt-2">
    <%= link_to admin_item_path(comment.item), class: "link-line" do %>
    <p class="mt-1 font-weight-bold text-secondary"><%= comment.item.name %></p>
    <% end %>
    <div id="rate-<%= comment.id %>"></div>
    <script>
          $('#rate-<%= comment.id %>').empty();
          $('#rate-<%= comment.id %>').raty({
            size: 36,
            readOnly: true,
            starOff:  '<%= asset_path('star-off.png') %>',
            starOn : '<%= asset_path('star-on.png') %>',
            starHalf: '<%= asset_path('star-half.png') %>',
            half: true,
            score: <%= comment.rate %>,
        });
    </script>
    <p class="border-top mt-2 text-secondary">レビュー：<%= comment.comment_content %></p>
    <div class="button text-right">
    <%= link_to "編集", edit_admin_comment_path(comment), class: 'btn btn-outline-success' %>
    <%= link_to "削除", admin_comment_path(comment), method: :delete, class: 'btn btn-outline-danger' %>
    </div>
   </div>
   <% end %>
   <div class="pagination col-sm-8 offset-sm-2 my-3">
    <%= paginate @comments %>
  </div>
   </div>
</div>
</div>