config/routes.rb
Rails.application.routes.draw do

  namespace :admin do
    resources :order_details, only:[:update]
  end

  namespace :admin do
    resources :orders, only:[:show, :update]
  end

  namespace :admin do
    resources :customers, only:[:index, :show, :edit, :update]
  end

  namespace :admin do
    resources :items, except: [:destroy] do
     resources :comments, only:[:index, :edit, :update, :destroy], shallow: true
    end
  end

  namespace :admin do
    get 'homes/top'
  end

  scope module: 'public' do
    get 'customers/mypage', to: 'customers#show'
    get 'customers/edit', to: 'customers#edit'
    patch 'customers/update'
    get 'customers/unsubscribe'
    patch 'customers/withdraw'
  end

  scope module: 'public' do
    get 'orders/thanks'
    post 'orders/confirm'
    resources :orders, only:[:new, :create, :index, :show]
  end
  scope module: 'public' do
    delete 'cart_items/empty'
    resources :cart_items, only:[:index, :create, :update, :destroy]
  end

  scope module: 'public' do
    get 'items/search'
    resources :items, only:[:index, :show] do
     resources :comments, except:[:show],shallow: true
    end
  end

  scope module: 'public' do
    root to: 'homes#top'
    get 'about', to: 'homes#about'
    get 'policy', to: 'homes#policy'
  end

  scope module: 'public' do
    resources :contacts, only: [:new, :create]
  end

devise_for :customers,skip: [:passwords], controllers: {
  registrations: "public/registrations",
  sessions: 'public/sessions'
}

devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
  sessions: "admin/sessions"
}

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
  
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
  belongs_to :item
  belongs_to :customer

  def subtotal
    item.add_tax_price * amount
  end
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :item
  belongs_to :customer


  validates :rate, numericality: {
    less_than_or_equal_to: 5,
    greater_than_or_equal_to: 0.5}, presence: true

  def avg_score
    unless self.comments.empty?
      comments.average(:rate_id).round(1)
    else
      0.0
    end
  end

  def avg_score_percentage
   unless self.comments.empty?
     comments.average(:rate_id).round(1).to_f*100/5
   else
     0.0
   end
  end

end

app/models/contact.rb
class Contact < ApplicationRecord
  validates :name, presence: true
  validates :content, presence: true
  validates :email, presence: true
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :name, presence: true
  validates :name_kana, presence: true
  validates :nickname, presence: true
  validates :email, presence: true
  validates :telephone_number, presence: true, numericality: { only_integer: true }
  validates :postal_code, presence: true, numericality: { only_integer: true }
  validates :address, presence: true
  validates :email, presence: true

  has_many :comments, dependent: :destroy
  has_many :cart_items
  has_many :orders
end

app/models/item.rb
class Item < ApplicationRecord
  has_one_attached :image_id
  has_many :cart_items
  has_many :order_details
  has_many :comments, dependent: :destroy

  def add_tax_price
  (self.price * 1.10).floor
  end

  def avg_score
    unless self.comments.empty?
      comments.average(:rate).round(1)
    else
      0.0
    end
  end

  def self.item_comment_ranks(limit)
    self.find(Comment.group(:item_id).order("rate DESC").pluck(:item_id)).first(limit)
  end

end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :customer
  has_many :order_details

  validates :postal_code, presence: true, numericality: { only_integer: true }
  validates :address, presence: true
  validates :name, presence: true

  enum payment: { credit_card: 0, transfer: 1 }
  enum shipping_status: { waiting: 0, paid: 1, shipped: 2 }

  def shipping_fee
    500.to_s
  end

  def add_tax_price
  (self.price * 1.10).floor
  end
end

app/models/order_detail.rb
class OrderDetail < ApplicationRecord
  belongs_to :item
  belongs_to :order

  enum status: { unstarted: 0, preparing: 1, completed: 2, shipped: 3}

  def add_tax_price
  (self.price * 1.10).floor
  end
end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController
  before_action :authenticate_admin!
  def top
    @orders = Order.all.page(params[:page]).per(10).order(created_at: :desc)
    @order_details = OrderDetail.all
  end

end

app/controllers/admin/items_controller.rb
class Admin::ItemsController < ApplicationController
  before_action :authenticate_admin!
  def index
    @items = Item.page(params[:page]).per(10)
  end

  def new
    @item = Item.new
  end

  def create
    @item = Item.new(item_params)
    if @item.save
     redirect_to admin_item_path(@item.id)
    else
     render :new
    end
  end

  def show
    @item = Item.find(params[:id])
    @comments = @item.comments
  end

  def edit
    @item = Item.find(params[:id])
  end

  def update
    @item = Item.find(params[:id])
    @item.update(item_params)
    redirect_to admin_item_path(@item.id)
  end

  private
  def item_params
    params.require(:item).permit(:image_id, :name, :volume, :price, :introduction, :blend_example, :blend_flag)
  end
end

app/controllers/admin/orders_controller.rb
class Admin::OrdersController < ApplicationController
  before_action :authenticate_admin!
  def show
    @order = Order.find(params[:id])
    @order_details = @order.order_details
  end

  def update
    @order = Order.find(params[:id])
    @order.update(order_params)
    @order_details = @order.order_details
     if @order.shipping_status == "paid"
      @order_details.each do |order_detail|
      order_detail.update(status: 1)
     end
     end
     redirect_to admin_order_path(@order.id)
  end

  private
  def order_params
   params.require(:order).permit(:shipping_status, :postal_code, :address, :name, :payment, :bill, :total)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?
  



  protected
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :name_kana, :postal_code, :address, :telephone_number, :nickname])
  end

  

end

app/helpers/admin/comments_helper.rb
module Admin::CommentsHelper
end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/helpers/admin/order_details_helper.rb
module Admin::OrderDetailsHelper
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/admin/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AromaStyle</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" type="text/css" href="//cdn.jsdelivr.net/npm/slick-carousel@1.8.1/slick/slick.css"/>
    <%= stylesheet_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script type="text/javascript" src="//cdn.jsdelivr.net/npm/slick-carousel@1.8.1/slick/slick.min.js"></script>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <script src="https://kit.fontawesome.com/fb8d9b2be6.js" crossorigin="anonymous"></script>
    <meta name="viewport" content="width=device-width, initial-scale=1.0, shrink-to-fit=no">

  </head>
　<div class="">
  <body class="hbc">
    <header>
    <% if customer_signed_in? %>
     <div class="container">
       <div class="row justify-content-center">
         <div class="leaf-image">
         <div class="logo m-4 text-center">
            <a class="navbar-brand" href="/"><%= image_tag 'logo_image.png' %></a>
         </div>
         </div>
       </div>
       <div class="row justify-content-center mb-4">
         <nav class="navbar col-sm-12 navbar-expand-lg">
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
           <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse justify-content-center" id="navbarNavDropdown">
           <ul class="navbar-nav mt-2">
            <li class=""><%= link_to about_path, class: "link" do %><p class="h5 font-weight-bold">About</p><p class="font-weight-normal">Aroma Styleについて</p><% end %></li>
            <li class="mx-2"><%= link_to items_path, class: "link" do %><p class="h5 font-weight-bold">Products</p><p class="font-weight-normal">商品一覧</p><% end %></li>
            <li class="mx-2"><%= link_to cart_items_path, class: "link" do %><p class="h5 font-weight-bold">Cart</p><p class="font-weight-normal">お買い物かご</p><% end %></li>
            <li class="mx-2"><%= link_to customers_mypage_path, class: "link" do %><p class="h5 font-weight-bold">My Page</p><p class="font-weight-normal">マイページ</p><% end %></li>
            <li class="mx-2"><%= link_to destroy_customer_session_path, method: :delete, class: "link" do %><p class="h5 font-weight-bold">Log Out</p><p class="font-weight-normal">ログアウト</p><% end %></li>
           </ul>
          </div>
         </nav>
         <div class="shipping-fee col-sm-12 text-center"><i class="fa-solid fa-truck"></i>   送料一律 ５００円 </div>
       </div>
     </div>
     <% elsif admin_signed_in? %>
     <div class="container">
       <div class="row justify-content-center">
         <div class="leaf-image">
         <div class="logo m-4 text-center">
            <a class="navbar-brand" href="/"><%= image_tag 'logo_image.png' %></a>
         </div>
         </div>
       </div>
       <div class="row justify-content-center mb-4">
         <nav class="navbar col-sm-10 navbar-expand-lg ">
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
           <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse justify-content-center" id="navbarNavDropdown">
           <ul class="navbar-nav mt-2">
            <li class="mx-2"><%= link_to admin_homes_top_path, class: "link" do %><p class="h5 font-weight-bold">Orders</p><p class="font-weight-normal">注文履歴一覧</p><% end %></li>
            <li class="mx-2"><%= link_to admin_customers_path, class: "link" do %><p class="h5 font-weight-bold">Customers</p><p class="font-weight-normal">顧客一覧</p><% end %></li>
            <li class="mx-2"><%= link_to admin_items_path, class: "link" do %><p class="h5 font-weight-bold">Products</p><p class="font-weight-normal">商品一覧</p><% end %></li>
            <li class="mx-2"><%= link_to destroy_admin_session_path, method: :delete, class: "link" do %><p class="h5 font-weight-bold">Log Out</p><p class="font-weight-normal">ログアウト</p><% end %></li>
           </ul>
          </div>
         </nav>
         <div class="shipping-fee col-sm-12 text-center"><i class="fa-solid fa-truck"></i> 送料一律 ５００円</div>
       </div>
     </div>
     <% else %>
     <div class="container">
       <div class="row justify-content-center">
         <div class="leaf-image">
         <div class="logo m-4 text-center">
            <a class="navbar-brand" href="/"><%= image_tag 'logo_image.png' %></a>
         </div>
         </div>
       </div>
       <div class="row mb-4">
         <nav class="navbar col-sm-10 offset-sm-1 navbar-expand-lg">
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
           <span class="navbar-toggler-icon "></span>
          </button>
          <div class="collapse navbar-collapse justify-content-center" id="navbarNavDropdown">
           <ul class="navbar-nav mt-2">
            <li class="mx-2"><%= link_to about_path, class: "link" do %><p class="h5 font-weight-bold">About</p><p class="font-weight-normal">Aroma Styleについて</p><% end %></li>
            <li class="mx-2"><%= link_to items_path, class: "link" do %><p class="h5 font-weight-bold">Products</p><p class="font-weight-normal">商品一覧</p><% end %></li>
            <li class="mx-2"><%= link_to new_customer_registration_path, class: "link" do %><p class="h5 font-weight-bold">Create Account</p><p class="font-weight-normal">新規会員登録</p><% end %></li>
            <li class="mx-2"><%= link_to customer_session_path, class: "link" do %><p class="h5 font-weight-bold">Log In</p><p class="font-weight-normal">ログイン</p><% end %></li>
           </ul>
          </div>
         </nav>
         <div class="shipping-fee col-sm-10 offset-sm-1 text-center"><i class="fa-solid fa-truck"></i> 送料一律 ５００円</div>
       </div>
      <% end %>
     </div>
    </header>
    <%= yield %>
  </div>
   <footer class="text-white pt-3">
      <div class="container">
        <div class="row  justify-content-center">
          <div class="f-navbar navbar-expand-lg">
            <ul class="navbar-nav mt-2">
                <li class="mx-3"><%= link_to policy_path, class: "link" do %><p class="footer-text font-weight-normal">Policy / ポリシー</p><% end %></li>
                <li class="mx-3"><%= link_to new_contact_path, class: "link" do %><p class="footer-text font-weight-normal">Contact / お問い合せ</p><% end %></li>
            </ul>
          </div>
        </div>
      </div>
    </footer>
  </body>
</html>